# Generated by Django 2.1 on 2019-01-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricetable1',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('f30', models.CharField(db_column='F30', max_length=50, unique=True)),
                ('f32', models.CharField(blank=True, db_column='F32', max_length=45, null=True)),
                ('f00', models.CharField(blank=True, db_column='F00', max_length=45, null=True)),
            ],
            options={
                'db_table': 'pricetable1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetable2',
            fields=[
                ('code', models.IntegerField(db_column='CODE', primary_key=True, serialize=False)),
                ('build_type', models.CharField(blank=True, db_column='BUILD_TYPE', max_length=45, null=True)),
            ],
            options={
                'db_table': 'pricetable2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetable3',
            fields=[
                ('code', models.IntegerField(db_column='CODE', primary_key=True, serialize=False)),
                ('build_type', models.CharField(blank=True, db_column='BUILD_TYPE', max_length=45, null=True)),
            ],
            options={
                'db_table': 'pricetable3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetable4',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pricetable4_f01', serialize=False, to='webpage.Pricetable1')),
                ('f02', models.TextField(blank=True, db_column='F02', null=True)),
                ('f03', models.FloatField(blank=True, db_column='F03', null=True)),
                ('f04', models.CharField(blank=True, db_column='F04', max_length=45, null=True)),
                ('f05', models.CharField(blank=True, db_column='F05', max_length=45, null=True)),
                ('f06', models.CharField(blank=True, db_column='F06', max_length=45, null=True)),
                ('f08', models.CharField(blank=True, db_column='F08', max_length=45, null=True)),
                ('f09', models.CharField(blank=True, db_column='F09', max_length=70, null=True)),
                ('f10', models.CharField(blank=True, db_column='F10', max_length=45, null=True)),
                ('f12', models.CharField(blank=True, db_column='F12', max_length=45, null=True)),
                ('f13', models.CharField(blank=True, db_column='F13', max_length=45, null=True)),
                ('f15', models.FloatField(blank=True, db_column='F15', null=True)),
            ],
            options={
                'db_table': 'pricetable4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetable5',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pricetable5_f01', serialize=False, to='webpage.Pricetable1')),
                ('f07', models.CharField(blank=True, db_column='F07', max_length=45, null=True)),
                ('f14', models.CharField(blank=True, db_column='F14', max_length=45, null=True)),
                ('f26', models.FloatField(blank=True, db_column='F26', null=True)),
                ('f27', models.FloatField(blank=True, db_column='F27', null=True)),
                ('f28', models.CharField(blank=True, db_column='F28', max_length=45, null=True)),
                ('f29', models.CharField(blank=True, db_column='F29', max_length=200, null=True)),
            ],
            options={
                'db_table': 'pricetable5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetable6',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pricetable6_f01', serialize=False, to='webpage.Pricetable1')),
                ('f16', models.CharField(blank=True, db_column='F16', max_length=45, null=True)),
                ('f17', models.CharField(blank=True, db_column='F17', max_length=45, null=True)),
                ('f18', models.CharField(blank=True, db_column='F18', max_length=45, null=True)),
                ('f19', models.CharField(blank=True, db_column='F19', max_length=45, null=True)),
                ('f20', models.CharField(blank=True, db_column='F20', max_length=45, null=True)),
                ('f23', models.CharField(blank=True, db_column='F23', max_length=45, null=True)),
                ('f24', models.FloatField(blank=True, db_column='F24', null=True)),
                ('f25', models.FloatField(blank=True, db_column='F25', null=True)),
            ],
            options={
                'db_table': 'pricetable6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricetable7',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pricetable7_f01', serialize=False, to='webpage.Pricetable1')),
                ('f21', models.FloatField(blank=True, db_column='F21', null=True)),
                ('f22', models.FloatField(blank=True, db_column='F22', null=True)),
                ('f21a', models.FloatField(blank=True, db_column='F21a', null=True)),
                ('f22a', models.FloatField(blank=True, db_column='F22a', null=True)),
                ('f21b', models.FloatField(blank=True, db_column='F21b', null=True)),
                ('f22b', models.FloatField(blank=True, db_column='F22b', null=True)),
                ('f22c', models.FloatField(blank=True, db_column='F22c', null=True)),
            ],
            options={
                'db_table': 'pricetable7',
                'managed': False,
            },
        ),
    ]
