# Generated by Django 2.1 on 2019-01-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleStatic',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('sp00', models.CharField(blank=True, db_column='SP00', max_length=5, null=True)),
                ('sp01', models.CharField(blank=True, db_column='SP01', max_length=50, null=True)),
                ('sp02', models.IntegerField(blank=True, db_column='SP02', null=True)),
                ('sp03', models.CharField(blank=True, db_column='SP03', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'People_Static',
            },
        ),
    ]
