# Generated by Django 2.1 on 2019-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_peoplestatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneySupply',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('m1b_money', models.IntegerField(blank=True, db_column='M1B_money', null=True)),
                ('m1b_money_rate', models.FloatField(blank=True, db_column='M1B_money_rate', null=True)),
                ('m2_money', models.IntegerField(blank=True, db_column='M2_money', null=True)),
                ('m2_money_rate', models.FloatField(blank=True, db_column='M2_money_rate', null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Money_Supply',
                'managed': False,
            },
        ),
    ]
